apiVersion: v1
kind: Pod
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  containers:
    - name: nestjs-app
      image: intro-k8s-medium:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret