apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: k8s-core-medium:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: ClusterIP
  selector:
    app: nestjs
  ports:
    - name: http
      port: 80
      targetPort: 3000

